
name: sidecar

volumes:
  sidecar_data:

services:
  sidecar:
    image: sidecar
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODEID=v2.sidecar
      - TRANSPORTER=nats://nats:4222
      - DOPPLER_TOKEN
    volumes:
      - sidecar_data:/usr/src/app/data
    ports:
      - "5103:5103"
    links:
      - nats
  nats:
    image: nats:latest
    command: -js
    