
services:
  lab:
    build: https://github.com/mishatre/moleculer-lab.git
    environment:
      - NODEID=lab
      - NAMESPACE=dev
      - TRANSPORTER=nats://nats:4222
      - MOL_TRACING__EVENTS=true
      - DOPPLER_TOKEN
    ports:
      - "3210:3210"
    links:
      - nats
  nats:
    image: nats:latest
    command:
      - -js
      - --name=dev-local
      - --cluster_name=NATS-dev
      - --cluster=nats://0.0.0.0:5222
      - --routes=nats://ruser:T0pS3cr3t@192.168.101.121:5222
    ports:
      - "4222:4222"
      - "5222:5222"