
services:
  lab:
    build: https://github.com/mishatre/moleculer-lab.git
    environment:
      - NODEID=lab
      - NAMESPACE=dev
      - TRANSPORTER=nats://nats:4222
      - MOL_TRACING__EVENTS=true
      - DOPPLER_TOKEN
    ports:
      - "3210:3210"
    links:
      - nats
  nats:
    image: nats:latest
    command:
      - --config=/tmp/server.conf
    volumes:
      - ./nats/server.conf:/tmp/server.conf
    ports:
      - "4222:4222"
      - "5222:5222"