name: moleculer-sidecar

services:
    moleculer-sidecar:
        image: ghcr.io/mishatre/moleculer-sidecar
        restart: unless-stopped
        env_file: .env
        environment:
            - NODEID=moleculer-sidecar
